src/Entity/Restaurant.php
<?php

namespace App\Entity;

use App\Repository\RestaurantRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\Criteria;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Symfony\Component\Validator\Constraints as Assert;
use Gedmo\Timestampable\Traits\Timestampable;

/**
 * @ORM\Entity(repositoryClass="App\Repository\RestaurantRepository")
 */
class Restaurant
{

    use Timestampable;
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     */
    private $name;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="array")
     */
    private $daysOpen;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $phone;

    /**
     * @ORM\Column(type="string")
     *
     * @Assert\NotBlank(message="Enter restaurant's image")
     * @Assert\File(mimeTypes={ "image/png", "image/jpeg" })
     */
    private $image;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $cuisine;

    /**
     * @ORM\Column(type="float")
     */
    private $stars=0;

    /**
     * @ORM\Column(type="datetime")
     */
    private $publishAt;





    /**
     * @ORM\Column(type="string", length=100,unique=true)
     * @Gedmo\Slug(fields={"name"})
     */
    private $slug;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Comment", mappedBy="restaurant" ,fetch="EXTRA_LAZY")
     * @ORM\OrderBy({"createdAt"="DESC"})
     */
    private $comments;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Category", inversedBy="restaurants")
     * @ORM\JoinColumn(nullable=false)
     */
    private $category;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="restaurants")
     * @ORM\JoinColumn(nullable=false)
     */
    private $owner;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isActive = true;

    /**
     * @Assert\NotBlank(message="Select at least one day")
     */
    private $arrayDaysArray;


    public function __construct()
    {
        $this->comments = new ArrayCollection();
    }


    /**
     * @return mixed
     */
    public function getPublishAt()
    {
        return $this->publishAt;
    }

    /**
     * @return mixed
     */
    public function getArrayDaysArray()
    {
        return $this->arrayDaysArray;
    }

    /**
     * @param mixed $arrayDaysArray
     * @return Restaurant
     */
    public function setArrayDaysArray($arrayDaysArray)
    {
        $this->arrayDaysArray = $arrayDaysArray;
        $this->setDaysOpen(implode(",",$arrayDaysArray));
        return $this;
    }


    /**
     * @param mixed $publishAt
     * @return Restaurant
     */
    public function setPublishAt($publishAt)
    {
        $this->publishAt = $publishAt;
        return $this;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getDaysOpen(): ?string
    {
        return $this->daysOpen;
    }

    public function setDaysOpen(string $daysOpen): self
    {
        $this->daysOpen = $daysOpen;

        return $this;
    }



    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(string $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getImage(): ?string
    {
        return $this->image;
    }

    /**
         * @param mixed $image
         * @return Restaurant
         */
    public function setImage(string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getCuisine(): ?string
    {
        return $this->cuisine;
    }

    public function setCuisine(string $cuisine): self
    {
        $this->cuisine = $cuisine;

        return $this;
    }

    public function getStars(): ?float
    {
        return $this->stars;
    }

    public function setStars(float $stars): self
    {
        $this->stars = $stars;

        return $this;
    }

    public function isOpen():bool{

        $dayofweek = date('w', time());
        return  strpos($this->getDaysOpen(), $dayofweek)!== false;
    }

    public function getHeartCount(): ?int
    {
        return $this->heartCount;
    }

    public function setHeartCount(int $heartCount): self
    {
        $this->heartCount = $heartCount;

        return $this;
    }



    public function getImagePath(){
        return 'images/restaurants/'.$this->getImage();
    }

    public function incrementHeartCount():self{
        $this->heartCount = $this->heartCount+1;
        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getNonDeletedComments(): Collection
    {
        return $this->comments->matching(RestaurantRepository::createNonDeletedCriteria());
    }



    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setRestaurant($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->contains($comment)) {
            $this->comments->removeElement($comment);
            // set the owning side to null (unless already changed)
            if ($comment->getRestaurant() === $this) {
                $comment->setRestaurant(null);
            }
        }

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }

    public function getOwner(): ?User
    {
        return $this->owner;
    }

    public function setOwner(?User $owner): self
    {
        $this->owner = $owner;

        return $this;
    }

    public function getIsActive(): ?bool
    {
        return $this->isActive;
    }

    public function setIsActive(bool $isActive): self
    {
        $this->isActive = $isActive;

        return $this;
    }


    public function isMine(User $user = null){
        if($user !=null)
            return $user == $this->owner;
        else
            return false;
    }



}

src/Controller/RestaurantController.php
<?php

namespace App\Controller;


use App\Entity\Category;
use App\Entity\Comment;
use App\Entity\Restaurant;
use App\Form\CommentFormType;
use App\Form\RestaurantFormType;
use App\Helpers\FileUploader;
use App\Repository\CategoryRepository;
use App\Repository\RestaurantRepository;
use Doctrine\ORM\EntityManagerInterface;
use Knp\Component\Pager\PaginatorInterface;
use Psr\Log\LoggerInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\File\File;

class RestaurantController extends AbstractController
{
    /**
     * @Route("/", name="app_homepage")
     */
    public function listAllRestaurants(RestaurantRepository $repositoryRestaurant,
                                       CategoryRepository $repositoryCategory,Request $request,
                                       PaginatorInterface $paginator)
    {


       // $restaurants =$repository->findBy([],['publisAt'=>'DESC']);
        /*
        $restaurants =$repositoryRestaurant->findAll();
        $categories = $repositoryCategory->findAll();
            //$repository->findAllOpen(2);
        return $this->render('restaurants/index.html.twig',[
            'restaurants'=>$restaurants,
            'categories'=>$categories
        ]);
        */
        $name = $request->query->get('name')??"";
        $categoria = $request->query->get('categoria')??"";
        $numberStar = $request->query->get('numberStar')??"";
        $open = $request->query->get('open')??"";
        $active = $request->query->get('active')??"";
        if(!$this->isGranted('ROLE_ADMIN')){
            $active = "Yes";
        }

        dump("name:".$name);
        dump("categoria:".$categoria);
        dump('estrellas'.$numberStar);
        dump("open".$open);



        // $restaurants =$repository->findBy([],['publisAt'=>'DESC']);
        $queryBuilder =$repositoryRestaurant->getWithSearchQueryBuilder($categoria,$numberStar,$name,$open,$active);

        $categories = $repositoryCategory->findAll();

        $pagination = $paginator->paginate(
            $queryBuilder, /* query NOT result */
            $request->query->getInt('page', 1)/*page number*/,
            10/*limit per page*/
        );

        return $this->render('restaurants/index.html.twig', [
            'pagination'=>$pagination,
            'categories'=>$categories
        ]);
    }

    /**
     * @Route("/add_restaurant", name="add_restaurant")
     * @IsGranted("ROLE_USER")
     */
    public function newRestaurant(EntityManagerInterface $em,
                                  Request $request,
                                  FileUploader $fileUploader){
        $form = $this->createForm(RestaurantFormType::class);

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $restaurant = $form->getData();

            /** @var UploadedFile $image */
            $image = $form->get('image')->getData();
            $fileName = $fileUploader->upload($image);

            $restaurant->setImage($fileName);
            $restaurant
                ->setOwner($this->getUser())
                ->setPublishAt(
                    new \DateTime());

            $em->persist($restaurant);
            $em->flush();
            $this->addFlash('success','New restaurant added');
            return $this->redirectToRoute('app_homepage');

        }

        return $this->render('restaurants/add_restaurant.html.twig', [
            'restaurantForm'=>$form->createView()
        ]);
    }

    /**
     * @Route("/restaurant/{slug}",name="restaurant_show")
     */
    public function detailRestaurant(Restaurant $restaurant, EntityManagerInterface $em,Request $request
    ,RestaurantRepository $repository){

        $formComment = $this->createForm(CommentFormType::class);
        $formComment->handleRequest($request);

        if ($formComment->isSubmitted() && $formComment->isValid()) {

            /** @var Comment $comment */
            $comment = $formComment->getData();
            $comment->setAuthor($this->getUser());
            $comment->setRestaurant($restaurant);
            $em->persist($comment);
            $em->flush();
            $puntacion = $repository->CurrentStars($restaurant);
            $restaurant->setStars($puntacion['rating']);
            $em->persist($restaurant);
            $em->flush($restaurant);

            $this->addFlash('success', 'Comment published');
        }

        return $this->render('restaurants/detail_restaurant.html.twig',
            [
                'restaurant'=>$restaurant,
                'form'=>$formComment->createView()
            ]);
    }




    /**
     * @Route("/restaurant/{slug}/heart", name="restaurant_heart",methods={"GET"})
     */
    public function likeRestaurant(Restaurant $restaurant,LoggerInterface $logger,
                                    EntityManagerInterface $em){
        $logger->info("Un restaurante ha recibido un like");

        $restaurant->incrementHeartCount();
        $em->flush();

        echo json_encode("DIOS");

    }

    /**
     * @Route("/restaurant/{id}/edit",name="restaurant_edit")
     * @IsGranted("ROLE_USER")
     */
    public function edit(Restaurant $restaurant,
                         Request $request,
                         FileUploader $fileUploader,
                         EntityManagerInterface $em)
    {

        $this->denyAccessUnlessGranted('MANAGE',$restaurant);
        $restaurant->setImage(
            new File($this->getParameter('images_directory').'/restaurants/'.$restaurant->getImage())
        );
        $array = explode(',', $restaurant->getDaysOpen());
        $restaurant->setArrayDaysArray($array);

        $form = $this->createForm(RestaurantFormType::class, $restaurant);

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $restaurant = $form->getData();

            /** @var UploadedFile $image */
            $image = $form->get('image')->getData();
            $fileName = $fileUploader->upload($image);
            $restaurant->setImage($fileName);


            $em->persist($restaurant);
            $em->flush();
            $this->addFlash('success', 'Restaurant updated');
            return $this->redirectToRoute('app_homepage');
        }
        return $this->render('restaurants/edit_restaurant.html.twig', [
            'restaurantForm'=>$form->createView()
        ]);
    }
    /**
     * @Route("/restaurant/{id}/delete",name="restaurant_delete")
     * @IsGranted("ROLE_USER")
     */
    public function delete(bool $borrado=true,Restaurant $restaurant){

        if (is_null($restaurant))
            throw new NotFoundHttpException('No se ha encontrado el contacto buscado');

        $em = $this->getDoctrine()->getManager();
        $restaurant->setIsActive(false);
        $em->persist($restaurant);
        $em->flush();
        return new JsonResponse(["true"=>true]);

    }


    /**
     * @Route("/restaurant/{id}/activate",name="restaurant_activate")
     * @IsGranted("ROLE_USER")
     */
    public function activate(bool $borrado=true,Restaurant $restaurant){

        if (is_null($restaurant))
            throw new NotFoundHttpException('No se ha encontrado el contacto buscado');

        $em = $this->getDoctrine()->getManager();
        $restaurant->setIsActive(true);
        $em->persist($restaurant);
        $em->flush();

        return new JsonResponse(["true"=>true]);

    }





}

templates/restaurants/add_restaurant.html.twig
{% extends 'partials/content_base.html.twig' %}





{% block content_body %}
    {% block form_title %}
        <h1>Adding new restaurant</h1>
    {% endblock %}
    {{ form_start(restaurantForm) }}
    {{ form_widget(restaurantForm) }}
    <button type="submit" class="btn btn-primary">Create!</button>
    {{ form_end(restaurantForm) }}
{% endblock %}

templates/restaurants/detail_restaurant.html.twig
{% form_theme form _self %}
{% extends 'partials/content_base.html.twig' %}

{% block title %}{{ restaurant.name }}'s Details{% endblock %}

{% block content_body %}

    <div id="cardContainer" class=" card mt-4">
        <img class="card-img-top"
            src="{{ asset(restaurant.imagePath) }}"
        >
        <div class="card-body">
            <h5 class="card-title">{{ restaurant.name  }}</h5>
            <p class="card-text">{{ restaurant.description }}</p>
            <div class="card-text">
                <small class="text-muted">
                    <strong>Opens: </strong> {{ restaurant.daysOpen|split(',')|daysName }}
                </small>

                {% if restaurant.isOpen() %}
                    <span class="badge badge-success">Abierto</span>
                {% else %}
                    <span class="badge badge-danger">Cerrado</span>
                {% endif %}
            </div>
            <div class="card-text">
                <small class="text-muted">
                    <strong>Telefono: </strong> {{ restaurant.phone }}
                </small>
            </div>
            <div class="card-text">
                <small class="text-muted">
                    <strong> Current Rating </strong> {{ restaurant.stars }}</strong>
                </small>
            </div>
            <p class="card-text"><small class="text-muted">Last updated
                    {{ restaurant.publishAt ? restaurant.publishAt | ago:'no publico  c' }}</small></p>


            <!--
            <? if ($restaurant->isMine()  || ( $app['user']!="" && $app['user']->getRol() ?? "" === 'ROLE_ADMIN')):?>
            <button class="mt-2 btn btn-sm btn-danger btn-delete" id="<?= $restaurant->getId() ?>">
                <?= _("Borrar")?></button>
            <a href="/edit-restaurant/<?=$restaurant->getId()?>">
                <button class="mt-2 btn btn-sm btn-info btn-info"><?= _("Editar")?></button>
            </a>
            </button>
            <?endif;?>

            -->

        </div>
        <div class="card-footer">
            <small class="text-muted">
                {{ restaurant.cuisine }}
            </small>
        </div>

    </div>

    <!-- COMENTARIOS -->
    <div class="row">
        <div class="col-sm-12">

            <ul class="list-group mt-4 mb-4" id="comments">
                <li class="list-group-item active">
                    <h3><i class="pr-3 fa fa-comment"></i>{{ restaurant.nonDeletedComments|length }} Comments</h3>
                    <hr>
                </li>
                {% for comment in restaurant.nonDeletedComments %}
                <li class="list-group-item d-flex flex-row">
                    <a href="{{ path('app_account_user',{id:comment.author.id}) }}">
                        <div>
                            <img class="comment-img rounded-circle" src="{{ asset(comment.author.getImagePath()) }}">
                        </div>
                    </a>

                    <div class="comment_text">
                        <span class="commenter-name">{{ comment.author.nickname }}</span>
                        <br>
                        <span class="comment"> {{ comment.content }}</span>
                        <div>
                            {%  for i  in 1..comment.stars if comment.stars != 0 %}
                                <i class="fa fa-star "></i>
                            {% endfor %}
                        </div>
                        <small>{{ comment.createdAt|ago }}</small>

                        {% if comment.isDeleted %}
                            <span class="fa fa-close"></span> deleted
                        {% endif %}
                    </div>


                </li>
                {% endfor %}
            </ul>

            {% if is_granted('ROLE_USER') %}

                <h4> Your opinion:</h4>
                {{ form_start(form,{
                    attr:{class:'mt-4'}
                }) }}
                {{ form_widget(form) }}
                {{ form_end(form) }}

            {% endif %}

        </div>
    </div>


{% endblock %}

{% block javascripts %}

    {{ parent() }}

    <script src="{{ asset('js/detail_restaurant.js') }}"></script>
{% endblock %}

templates/restaurants/edit_restaurant.html.twig
{% extends 'restaurants/add_restaurant.html.twig' %}

{% block form_title %}
    <h1>Update  restaurant</h1>
{% endblock %}

templates/restaurants/index.html.twig
{% extends 'base.html.twig' %}



{% block body %}


    <div class="container p-3 mt-4">

    {% include 'partials/search_input.part.html.twig' with {menuType:categories, menuType:app} %}
    {% include 'partials/list_restaurant.part.html.twig' with {menuType:pagination}   %}
    </div>

{% endblock %}

{% block javascripts %}

    {{ parent() }}

    <script src="{{ asset('js/delete.js') }}"></script>
{% endblock %}